### ISSUE TITLE
Not Working for iOS

### ISSUE THREAD

**Issue by danielmoro** [mattt/TransformerKit#45]
In podspec says:
s.ios.deployment_target = '5.0'
But TransformerKit cannot be compiled for iOS because security framework is required for data transformers for some reason. Security framework on iOS lacks required functions.

**Comment by mattt** [comment]
I do not have any issues installing on iOS. If you do, however, you can work around them by specifying only the subspecs that you're using:

```ruby
pod "TransformerKit/String"
```
